language: node_js
node_js:
- '8'
before_script:
- sudo apt-get install imagemagick
script:
- bash generate.sh kalisio assets
- bash generate.sh kargo assets
- bash generate.sh kano assets
- bash generate.sh kaabah assets
- bash generate2.sh crisis assets
- bash generate2.sh field assets
- bash generate2.sh kapp assets
- bash generate2.sh kdk assets
- bash generate2.sh krawler assets
- bash generate2.sh maps assets
- bash generate2.sh planet assets
- bash generate2.sh skeleton assets
- bash generate2.sh planet assets
- bash generate2.sh teams assets
- bash generate2.sh watch assets
- bash generate2.sh weacast assets
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kalisioscope
  local_dir: assets
  acl: public_read
    

