language: node_js
node_js:
- '8'
before_script:
- sudo apt-get install imagemagick
script:
- bash generate.sh kalisio assets
- bash generate.sh aktnmap assets
- bash generate.sh kargo assets
- bash generate.sh krawler assets
- bash generate.sh kdk assets
- bash generate.sh weacast assets
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kalisioscope2
  local_dir: assets
    

