language: node_js
node_js:
- '8'

notifications:
  slack:
    rooms:
      secure: B4ZE2Bh0YRPKpoBLqf7ZDNjrMQSmv4ZytQ8/f+5sYIOYaBnWh8CmC3adLmNvVS6qyb3DhPVC4lXNNN4+HjkIkFQGfKsQBKMEWC4HuKwhvR4Q2JBwmWpYXzR/jJaSSsLkyJYQg7iVAV0kthDstuocx0mlicUHLo8Piv9Es0N6TgYkl4lVeylJL9+dI+t2gMHlOZvy8zXUhuuBkUMCb6rJSYu0GL8gDFRHJZSEiUKPHT6bHVUPC5f4W8sZKrI4InPD7WdNntvHlPhby2huA2LjmGcWKxEU9em1RzS05FKwswqnXKIN30+gLQJt4JpDiHc/e8b767m+mNAjlCJ0g1Pk4bgVREluukjmB+3a15uJhAaGZE1hBAdwbH893b7/mbm5yF7yDvf+iUet99vozNYI01kxZQvvKqKKvIPWf9e+vojb3/0VqP0U58kVzrr9miJegcORMqjL5udz278JgA4T+iSS4qWQDLdBnL3sKbWgXfl9RHknUaGmZemchHhVu5FVPXmyglnzAhjpTEAuTRnQaEE+rqZ2A1qIwY8MLeEFRnYWRBRxvG0/MRBLGSwu3ES8vEP1rHqzKKGLAC7vm6DmHVlbxq57lELt+Hf4bNchBYl9CrLsG2AJdupti3hsLyqrMrNQbeWKPufnbKpiIPKC9PKmSYdw403MwC+5zrKE0vI=

before_script:
- sudo apt-get install imagemagick

script:
- bash generate.sh kalisio assets
- bash generate.sh kargo assets
- bash generate.sh kano assets
- bash generate.sh kaabah assets
- bash generate2.sh crisis assets
- bash generate2.sh field assets
- bash generate2.sh kapp assets
- bash generate2.sh kdk assets
- bash generate2.sh krawler assets
- bash generate2.sh maps assets
- bash generate2.sh planet assets
- bash generate2.sh skeleton assets
- bash generate2.sh planet assets
- bash generate2.sh teams assets
- bash generate2.sh watch assets
- bash generate2.sh weacast assets

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: kalisioscope
  local_dir: assets
  acl: public_read
